# Generated by Django 4.1.7 on 2023-03-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created',)},
        ),
    ]
