# Generated by Django 4.1.7 on 2023-03-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
